export const CART_ADD_ITEM = "CART_ADD_ITEM";
export const CART_REMOVE_ITEM = "CART_REMOVE_ITEM";
export const ADD_SHIPMENT_DETAILS = "ADD_SHIPMENT_DETAILS";
export const PAYMENT_METHOD = "PAYMENT_METHOD";